# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZHKitDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZHKitDemo
  pod 'Alamofire'
  pod 'SnapKit'
  pod 'SocketRocket'

end
